# Generated by Django 5.0.6 on 2026-08-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='album_sort_by',
            field=models.CharField(default='newest', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='audio_quality',
            field=models.CharField(default='high', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='song_sort_by',
            field=models.CharField(default='newest', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='volume',
            field=models.FloatField(default=1.0),
        ),
    ]
