# Generated by Django 5.0.6 on 2026-08-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_album_sort_by_user_audio_quality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crossfade_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='repeat_mode',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='shuffle',
            field=models.BooleanField(default=False),
        ),
    ]
