# Generated by Django 5.0.6 on 2026-08-09 18:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/albums/')),
                ('genre', models.CharField(blank=True, max_length=80)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(limit_choices_to={'role': 'artist'}, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='songs/')),
                ('audio_format', models.CharField(choices=[('mp3', 'MP3'), ('wav', 'WAV'), ('flac', 'FLAC')], default='mp3', max_length=8)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/songs/')),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('genre', models.CharField(blank=True, max_length=80)),
                ('lyrics', models.TextField(blank=True)),
                ('featured_artist_names', models.CharField(blank=True, max_length=255)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='catalog.album')),
                ('artist', models.ForeignKey(limit_choices_to={'role': 'artist'}, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='StreamLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streamed_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='catalog.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['song', 'streamed_at'], name='catalog_str_song_id_713660_idx'), models.Index(fields=['user', 'streamed_at'], name='catalog_str_user_id_22f825_idx')],
            },
        ),
    ]
