# Generated by Django 5.0.6 on 2026-08-13 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file_low',
            field=models.FileField(blank=True, help_text='فایل کیفیت پایین LQ (128kbps)', null=True, upload_to='songs/low/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, help_text='فایل اصلی / کیفیت بالا HQ (320kbps)', null=True, upload_to='songs/'),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_quality', models.CharField(choices=[('high', 'High (320kbps)'), ('low', 'Low (128kbps)')], default='high', max_length=10)),
                ('crossfade_enabled', models.BooleanField(default=False)),
                ('crossfade_duration', models.PositiveIntegerField(default=5)),
                ('volume', models.FloatField(default=1.0)),
                ('autoplay', models.BooleanField(default=True)),
                ('repeat_mode', models.CharField(choices=[('off', 'Off'), ('one', 'Repeat One'), ('all', 'Repeat All')], default='off', max_length=10)),
                ('shuffle_enabled', models.BooleanField(default=False)),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('system', 'System')], default='dark', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
