# Generated by Django 5.0.6 on 2026-08-09 18:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('basic', 'Basic (free)'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=10, unique=True)),
                ('price_monthly', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('max_playlists', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_stream_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('can_change_avatar', models.BooleanField(default=False)),
                ('can_download', models.BooleanField(default=False)),
                ('early_access', models.BooleanField(default=False)),
                ('can_view_stats', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period_months', models.PositiveSmallIntegerField(choices=[(1, '1 month(s)'), (3, '3 month(s)'), (6, '6 month(s)'), (12, '12 month(s)')])),
                ('price_paid', models.DecimalField(decimal_places=0, max_digits=10)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='subscriptions.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
